insert into products (name, price) values ('Bread Crumbs - Panko', 69.5);
insert into products (name, price) values ('Pork - Liver', 94.17);
insert into products (name, price) values ('Lemonade - Black Cherry, 591 Ml', 67.15);
insert into products (name, price) values ('Quiche Assorted', 36.13);
insert into products (name, price) values ('Dr. Pepper - 355ml', 7.8);
insert into products (name, price) values ('Flower - Carnations', 13.25);
insert into products (name, price) values ('Yoghurt Tubes', 93.26);
insert into products (name, price) values ('Cheese - St. Paulin', 94.01);
insert into products (name, price) values ('Beans - Soya Bean', 24.67);
insert into products (name, price) values ('Pepper - Black, Whole', 37.23);
insert into products (name, price) values ('Gatorade - Orange', 25.07);
insert into products (name, price) values ('Cup - 3.5oz, Foam', 6.05);
insert into products (name, price) values ('Nut - Almond, Blanched, Whole', 9.44);
insert into products (name, price) values ('Nut - Pistachio, Shelled', 75.12);
insert into products (name, price) values ('Lettuce - Radicchio', 63.05);
insert into products (name, price) values ('Grenadine', 90.36);
insert into products (name, price) values ('Placemat - Scallop, White', 16.55);
insert into products (name, price) values ('Cheese - Montery Jack', 61.32);
insert into products (name, price) values ('Wine - Red, Gamay Noir', 24.98);
insert into products (name, price) values ('Corn - On The Cob', 65.17);
insert into products (name, price) values ('Wine - White, Pinot Grigio', 35.35);
insert into products (name, price) values ('Carbonated Water - White Grape', 79.2);
insert into products (name, price) values ('Soap - Mr.clean Floor Soap', 5.58);
insert into products (name, price) values ('Water Chestnut - Canned', 20.47);
insert into products (name, price) values ('Bagel - Plain', 39.4);
insert into products (name, price) values ('Yogurt - French Vanilla', 59.86);
insert into products (name, price) values ('Creme De Banane - Marie', 59.16);
insert into products (name, price) values ('Kaffir Lime Leaves', 78.62);
insert into products (name, price) values ('Carbonated Water - Blackberry', 68.53);
insert into products (name, price) values ('Country Roll', 25.3);
insert into products (name, price) values ('Sole - Dover, Whole, Fresh', 54.37);
insert into products (name, price) values ('Crab - Blue, Frozen', 85.65);
insert into products (name, price) values ('Vector Energy Bar', 26.6);
insert into products (name, price) values ('Tea - Mint', 13.14);
insert into products (name, price) values ('Bread - Roll, Calabrese', 97.5);
insert into products (name, price) values ('Bread - Hamburger Buns', 22.22);
insert into products (name, price) values ('Miso Paste White', 92.19);
insert into products (name, price) values ('Filter - Coffee', 30.53);
insert into products (name, price) values ('Potatoes - Yukon Gold 5 Oz', 63.54);
insert into products (name, price) values ('Butter Sweet', 98.51);
insert into products (name, price) values ('Garlic - Primerba, Paste', 20.25);
insert into products (name, price) values ('Nantucket - Orange Mango Cktl', 25.41);
insert into products (name, price) values ('Wine - Delicato Merlot', 49.11);
insert into products (name, price) values ('Grapefruit - Pink', 71.95);
insert into products (name, price) values ('Pizza Pizza Dough', 48.77);
insert into products (name, price) values ('Dates', 51.07);
insert into products (name, price) values ('Cheese - Stilton', 93.6);
insert into products (name, price) values ('Pants Custom Dry Clean', 1.59);
insert into products (name, price) values ('Orange - Blood', 86.97);
insert into products (name, price) values ('Sterno - Chafing Dish Fuel', 95.8);
insert into products (name, price) values ('Dried Apple', 78.23);
insert into products (name, price) values ('Cup Translucent 9 Oz', 56.26);
insert into products (name, price) values ('Venison - Denver Leg Boneless', 81.4);
insert into products (name, price) values ('Bread - Raisin', 58.55);
insert into products (name, price) values ('Sauce - Caesar Dressing', 3.15);
insert into products (name, price) values ('Nori Sea Weed - Gold Label', 38.06);
insert into products (name, price) values ('Croissant, Raw - Mini', 44.5);
insert into products (name, price) values ('Coke - Diet, 355 Ml', 33.83);
insert into products (name, price) values ('Appetizer - Seafood Assortment', 39.42);
insert into products (name, price) values ('Bar Mix - Lime', 79.55);
insert into products (name, price) values ('Pepper - Red Thai', 29.24);
insert into products (name, price) values ('Sobe - Green Tea', 5.87);
insert into products (name, price) values ('Cheese - Feta', 47.44);
insert into products (name, price) values ('Beef - Ground, Extra Lean, Fresh', 66.79);
insert into products (name, price) values ('Pork - Backs - Boneless', 29.25);
insert into products (name, price) values ('Momiji Oroshi Chili Sauce', 42.65);
insert into products (name, price) values ('Edible Flower - Mixed', 92.99);
insert into products (name, price) values ('Appetizer - Asian Shrimp Roll', 92.51);
insert into products (name, price) values ('Nori Sea Weed', 28.88);
insert into products (name, price) values ('Chips - Potato Jalapeno', 18.42);
insert into products (name, price) values ('Wine - Chardonnay South', 75.39);
insert into products (name, price) values ('Pastry - Chocolate Chip Muffin', 78.62);
insert into products (name, price) values ('Crab - Back Fin Meat, Canned', 74.89);
insert into products (name, price) values ('Flour - Corn, Fine', 39.93);
insert into products (name, price) values ('Couscous', 48.98);
insert into products (name, price) values ('Pails With Lids', 26.63);
insert into products (name, price) values ('Pie Box - Cello Window 2.5', 20.36);
insert into products (name, price) values ('Nantucket - Kiwi Berry Cktl.', 73.46);
insert into products (name, price) values ('Coffee - Irish Cream', 24.27);
insert into products (name, price) values ('Pepper - Jalapeno', 48.24);
insert into products (name, price) values ('Wine - Manischewitz Concord', 58.48);
insert into products (name, price) values ('Yukon Jack', 52.38);
insert into products (name, price) values ('Potatoes - Yukon Gold, 80 Ct', 86.84);
insert into products (name, price) values ('Wine - Maipo Valle Cabernet', 13.11);
insert into products (name, price) values ('Rum - Coconut, Malibu', 32.86);
insert into products (name, price) values ('Blueberries', 63.63);
insert into products (name, price) values ('Potatoes - Pei 10 Oz', 28.69);
insert into products (name, price) values ('Strawberries', 64.84);
insert into products (name, price) values ('Pasta - Lasagna Noodle, Frozen', 6.65);
insert into products (name, price) values ('Vinegar - Champagne', 23.84);
insert into products (name, price) values ('Vector Energy Bar', 83.83);
insert into products (name, price) values ('Tarragon - Fresh', 84.8);
insert into products (name, price) values ('Sauce - Hoisin', 22.44);
insert into products (name, price) values ('Wine - Wyndham Estate Bin 777', 89.55);
insert into products (name, price) values ('Langers - Mango Nectar', 55.09);
insert into products (name, price) values ('Trout - Smoked', 97.76);
insert into products (name, price) values ('Broccoli - Fresh', 36.87);
insert into products (name, price) values ('Guava', 95.19);
insert into products (name, price) values ('Beer - Sleeman Fine Porter', 7.46);
insert into products (name, price) values ('Beer - Budweiser', 8.12);